name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g yarn
      - run: yarn --pure-lockfile
      - name: linter
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint_flags: ./src --ext .ts --ext .tsx
          reporter: github-check
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g yarn
      - run: yarn --pure-lockfile
        name: Install dependencies
      - run: yarn test --coverage
        name: Run tests
        env:
          CI: true
